/**
 * E2E tests for the scenario report generator (REQ-12).
 *
 * These tests instantiate LiveEngine, advance the simulation, and verify
 * that generateReport() produces valid, complete Markdown reports.
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { LiveEngine } from '../simulation/live-engine.js';
import {
  generateReport,
  getReport,
  addSnapshot,
  resetAccumulator,
  accumulateSample,
} from '../reports/report-generator.js';
import type { ReportOptions, MapSnapshot } from '../reports/report-generator.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Advance the engine by seeking to `toSec`. This replays the scenario
 * synchronously from t=0 to t=toSec, processing all events along the way.
 */
function advanceEngine(engine: LiveEngine, toSec: number): void {
  // State machine: idle → running → paused → seeking → paused
  engine.start();
  engine.pause();
  engine.seek(toSec);
}

const OPERATOR_OPTIONS: ReportOptions = { type: 'operator' };
const INSTRUCTOR_OPTIONS: ReportOptions = { type: 'instructor' };

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('Scenario Report E2E', () => {
  let engine: LiveEngine;

  beforeEach(() => {
    // Reset the module-level accumulator between tests
    resetAccumulator();
    // Create a fresh engine using the default central-israel scenario
    engine = new LiveEngine();
  });

  afterEach(() => {
    // Clean up any running timers
    try {
      engine.pause();
    } catch {
      // ignore if not running
    }
  });

  // 1. Report generation after scenario run
  it('generates a non-empty markdown report after running the scenario', () => {
    advanceEngine(engine, 20);

    const report = generateReport(engine, OPERATOR_OPTIONS);

    expect(report).toBeDefined();
    expect(report.id).toMatch(/^report-/);
    expect(report.type).toBe('operator');
    expect(report.content.length).toBeGreaterThan(100);
    expect(report.generatedAt).toBeGreaterThan(0);
    // Should start with the top-level heading
    expect(report.content).toContain('# ELOC2 Scenario Report');
    expect(report.content).toContain('**Report Type:** Operator Report');
  });

  // 2. Report sections verification
  it('contains all expected sections in the instructor report', () => {
    advanceEngine(engine, 20);

    const report = generateReport(engine, INSTRUCTOR_OPTIONS);
    const content = report.content;

    expect(report.type).toBe('instructor');
    expect(content).toContain('**Report Type:** Instructor Report');

    // Section 1: Scenario Definition
    expect(content).toContain('## 1. Scenario Definition');
    expect(content).toMatch(/Targets\s*\|\s*\d+/);
    expect(content).toMatch(/Sensors\s*\|\s*\d+/);

    // Section 2: Ground Truth Summary
    expect(content).toContain('## 2. Ground Truth Summary');

    // Section 3: System Performance Timeline
    expect(content).toContain('## 3. System Performance Timeline');
    expect(content).toContain('Total Tracks');

    // Section 4: EO Investigation Summary
    expect(content).toContain('## 4. EO Investigation Summary');
    expect(content).toContain('Tasking');

    // Section 5: Quality Metrics
    expect(content).toContain('## 5. Quality Metrics');

    // Section 6: Situational Awareness
    expect(content).toContain('## 6. Situational Awareness Assessment');

    // Conclusions
    expect(content).toContain('## Conclusions & Key Statistics');
    expect(content).toContain('Report generated by ELOC2 Report Generator');
  });

  // 3. Snapshot handling
  it('includes snapshot references when snapshots are added', () => {
    advanceEngine(engine, 10);

    const snapshot: MapSnapshot = {
      imageData: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUg==',
      label: 'Test Snapshot at T+10',
      timestamp: Date.now(),
    };
    addSnapshot(snapshot);

    const report = generateReport(engine, OPERATOR_OPTIONS);

    // The report should be generated successfully even with snapshots stored.
    // Snapshots are stored module-level; the report generator may or may not
    // embed them directly, but the generation must succeed.
    expect(report.content).toBeDefined();
    expect(report.content.length).toBeGreaterThan(0);
  });

  // 4. Report storage and retrieval
  it('stores and retrieves reports by ID', () => {
    advanceEngine(engine, 15);

    const report = generateReport(engine, OPERATOR_OPTIONS);
    const retrieved = getReport(report.id);

    expect(retrieved).toBeDefined();
    expect(retrieved!.id).toBe(report.id);
    expect(retrieved!.content).toBe(report.content);
    expect(retrieved!.type).toBe('operator');
    expect(retrieved!.generatedAt).toBe(report.generatedAt);
  });

  // 5. Empty scenario report
  it('produces valid markdown without running the scenario (t=0)', () => {
    // Do not advance the engine — generate report from initial state
    // Need to start/pause to get out of idle for any state reads
    const report = generateReport(engine, OPERATOR_OPTIONS);
    const content = report.content;

    // Should still have valid structure
    expect(content).toContain('# ELOC2 Scenario Report');
    expect(content).toContain('## 1. Scenario Definition');
    expect(content).toContain('## Conclusions & Key Statistics');
    // Track count should be zero
    expect(content).toMatch(/Total Tracks\s*\|\s*0/);
  });

  // 6. Accumulator reset
  it('produces minimal data after accumulator reset', () => {
    // Advance and accumulate samples
    advanceEngine(engine, 25);

    // Manually accumulate several samples
    for (let i = 0; i < 20; i++) {
      accumulateSample(engine);
    }

    // Reset the accumulator
    resetAccumulator();

    // Generate report — timeline section should have no accumulated samples
    const report = generateReport(engine, OPERATOR_OPTIONS);
    const content = report.content;

    // The performance timeline section should exist but have no "Track Count Over Time" table
    // because accumulated samples were cleared.
    expect(content).toContain('## 3. System Performance Timeline');
    // The "Track Count Over Time" sub-heading only appears if timelineSamples.length > 0
    expect(content).not.toContain('### Track Count Over Time');
  });

  // 7. Selective sections
  it('generates report with only selected sections', () => {
    advanceEngine(engine, 10);

    const report = generateReport(engine, {
      type: 'operator',
      sections: ['scenario', 'conclusions'],
    });
    const content = report.content;

    expect(content).toContain('## 1. Scenario Definition');
    expect(content).toContain('## Conclusions & Key Statistics');
    // Should NOT contain omitted sections
    expect(content).not.toContain('## 3. System Performance Timeline');
    expect(content).not.toContain('## 4. EO Investigation Summary');
    expect(content).not.toContain('## 5. Quality Metrics');
  });

  // 8. Retrieval of nonexistent report returns undefined
  it('returns undefined for a nonexistent report ID', () => {
    const result = getReport('nonexistent-report-id');
    expect(result).toBeUndefined();
  });
});
